"""Shared role constants for permission checks."""

from os import getenv

SUPER_ADMIN = "SUPER_ADMIN"
ADMIN = "ADMIN"
ADMIN_GLOSSAIRE = "ADMIN_GLOSSAIRE"
DATA_OWNER = "DATA_OWNER"
AUDIT = "AUDIT"

# Role groups
ADMINISTRATORS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE}
PROJECT_CREATORS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE, DATA_OWNER}
GLOSSARY_MANAGERS = {SUPER_ADMIN, ADMIN_GLOSSAIRE}
USER_MANAGERS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE}
CRITICAL_ROLES = {SUPER_ADMIN, ADMIN_GLOSSAIRE}
ALL_ROLES = [SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE, DATA_OWNER, AUDIT]

MAX_SUPER_ADMINS = int(getenv("MAX_SUPER_ADMINS", "2"))
MAX_ADMIN_GLOSSAIRES = int(getenv("MAX_ADMIN_GLOSSAIRES", "2"))

ROLE_LIMITS = {
    SUPER_ADMIN: MAX_SUPER_ADMINS,
    ADMIN_GLOSSAIRE: MAX_ADMIN_GLOSSAIRES,
}


def is_valid_role(role: str) -> bool:
    return role in ALL_ROLES
