"""Shared role constants for permission checks."""

SUPER_ADMIN = "SUPER_ADMIN"
ADMIN = "ADMIN"
ADMIN_GLOSSAIRE = "ADMIN_GLOSSAIRE"
DATA_OWNER = "DATA_OWNER"
AUDIT = "AUDIT"

# Role groups
ADMINISTRATORS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE}
PROJECT_CREATORS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE, DATA_OWNER}
GLOSSARY_MANAGERS = {SUPER_ADMIN, ADMIN_GLOSSAIRE}
USER_MANAGERS = {SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE}
ALL_ROLES = [SUPER_ADMIN, ADMIN, ADMIN_GLOSSAIRE, DATA_OWNER, AUDIT]


def is_valid_role(role: str) -> bool:
    return role in ALL_ROLES
