apiVersion: 1

datasources:
  - name: PFE Postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: ${GF_POSTGRES_HOST}:${GF_POSTGRES_PORT}
    user: ${GF_POSTGRES_USER}
    secureJsonData:
      password: ${GF_POSTGRES_PASSWORD}
    jsonData:
      database: ${GF_POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false

